In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense,Flatten,Dropout
from keras.models import Sequential

In [2]:
from keras.datasets import mnist

In [3]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)
#training set consist of 60000 images each of size 28*28 pixels and testing set consists of 10000 images each of size 28*28

(60000, 28, 28) (10000, 28, 28)
(60000,) (10000,)


In [7]:
x_train = x_train.reshape(x_train.shape[0],28,28,1)
x_test = x_test.reshape(x_test.shape[0],28,28,1) #converting images in grayscale
input_data = (28,28,1)
y_train = keras.utils.to_categorical(y_train) #y_train has values like 5,9,3,1 according to classification . now it is converted in 0's and 1's which mnist no is true that is one rest is 0
y_test = keras.utils.to_categorical(y_test)

In [9]:
y_train[0] #5

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [10]:
y_train[1011] #2

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [11]:
#preprocessing using minmax normalization
x_train = x_train/255.0
x_test = x_test/255.0

In [16]:
#model buildong
def build_model(optimizer):
  model = Sequential()
  model.add(Flatten()) #2d to 1d i.e matrix to vector
  model.add(Dense(256,activation = "relu",input_shape = input_data))
  model.add(Dropout(0.3))
  model.add(Dense(256,activation = "relu"))
  model.add(Dropout(0.4))
  model.add(Dense(10,activation = "softmax"))
  model.compile(optimizer = optimizer,loss = keras.losses.categorical_crossentropy,metrics = ["accuracy"])
  return model


In [19]:
optimizer = ["SGD","Adagrad","Adadelta","RMSprop","Adam"]
for i in optimizer:
  model = build_model(i)
  print('Running epochs for optimizer:',i)
  history = model.fit(x_train,y_train,validation_data = (x_test,y_test),batch_size = 32,verbose = 1,epochs = 10)


Running epochs for optimizer: SGD
Epoch 1/10
1875/1875 [==============================] - 9s 4ms/step - loss: 0.8097 - accuracy: 0.7531 - val_loss: 0.3193 - val_accuracy: 0.9091
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3921 - accuracy: 0.8848 - val_loss: 0.2457 - val_accuracy: 0.9290
Epoch 3/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3174 - accuracy: 0.9064 - val_loss: 0.2075 - val_accuracy: 0.9387
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2731 - accuracy: 0.9200 - val_loss: 0.1814 - val_accuracy: 0.9453
Epoch 5/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2416 - accuracy: 0.9294 - val_loss: 0.1617 - val_accuracy: 0.9504
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2165 - accuracy: 0.9372 - val_loss: 0.1462 - val_accuracy: 0.9556
Epoch 7/10
1875/1875 [==============================] - 10s 6ms/step - loss: 0.1973 - accuracy: 0.9423

 For SGD : loss: 0.1618 - accuracy: 0.9522 - val_loss: 0.1111 - val_accuracy: 0.
9667
For AdaGrad : loss: 0.3770 - accuracy: 0.8893 - val_loss: 0.2673 - val_accuracy: 0.9232
For AdaDelta : loss: 1.3994 - accuracy: 0.6317 - val_loss: 1.1899 - val_accuracy: 0.7964
For RMSProp : loss: 0.1015 - accuracy: 0.9773 - val_loss: 0.1082 - val_accuracy: 0.9821
For ADAM : loss: 0.0612 - accuracy: 0.9809 - val_loss: 0.0638 - val_accuracy: 0.9818 --->Best


---

